### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [antropovaa/AddressBook#1]
1. Из методов поиска лучше возвращать объект класса `Address`, а не строку. В таком случае в клиентском коде для вашего класса не придётся разбирать строку на компоненты, если это понадобится. Получение строкового представления для адреса лучше сделать переопределив метод `toString()` класса `Address`.
2. Вместо связки `keySet()` + `get()` (в `searchByStreet` и `searchByBuilding`) лучше использовать `entrySet()`. Так при итерации у вас сразу будут и ключ и значение и не нужно будет дополнительно получать значение по ключу из `Map`.
3.  Немного кривые отступы в `searchByStreet `

**Comment by JohnKhandygo** [comment]
- [ ] В коде `AdressBook` есть неиспользуемые параметры
- [ ] Реализации методов `searchByStreet` и  `searchByBuilding` практически идентичны. В таком случае стоит обобщить оба метода в один и использовать этот новый метод для реализации обеих функций.
